# Generated by Django 5.1.1 on 2025-10-30 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username 150 символов', regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
