# Generated by Django 5.1.1 on 2025-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_titles_genre_titles_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(),
        ),
    ]
