# Generated by Django 5.1.1 on 2025-10-29 08:29

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_genre_slug'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.CheckConstraint(condition=models.Q(('year__lt', django.db.models.functions.datetime.ExtractYear(django.db.models.functions.datetime.Now()))), name='year_less_than_current'),
        ),
    ]
