# Generated by Django 5.1.1 on 2025-10-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_titles_year_less_than_current'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titles',
            name='year_less_than_current',
        ),
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.CheckConstraint(condition=models.Q(('year__lt', 2025)), name='year_less_than_current'),
        ),
    ]
