# Generated by Django 5.1.1 on 2025-10-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_titles_year_less_than_current_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titles',
            name='year_less_than_current',
        ),
    ]
